**/node_modules
**/.next
**/.turbo
.turbo
.git
.github

**/.env
**/.env.*
!.env.example
!.env.production.example
.vscode
.idea

docs
.planning
deployment
**/*.test.ts
**/*.test.tsx
*.png
*.md
!README.md
.cursor
